# official Python image as the base
FROM python:3.8-slim

# environment variables
ENV PYTHONUNBUFFERED=1 \
    POETRY_VERSION=1.1.13

#system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Installing Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

# Setting the working directory
WORKDIR /app

COPY . .

RUN poetry install --no-root --no-dev

EXPOSE 8000

# Start the FastAPI server
CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
